project_core_homepage:
    path:     /
    defaults: { _controller: ProjectCoreBundle:Default:index }


project_core_hardcoded_requests:
    resource: "@ProjectCoreBundle/Resources/config/routing/request.yml"
    prefix:   /request/

project_core_user_agents:
    resource: "@ProjectCoreBundle/Resources/config/routing/user_agent.yml"
    prefix:   /user-agent/
